services:
  - type: web
    name: zitoun-pos-api
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: .
    plan: free
    region: frankfurt
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false

  - type: web
    name: zitoun-pos-angular
    runtime: node
    region: frankfurt
    rootDir: ./angular-app
    buildCommand: npm install && node_modules/.bin/ng build --configuration=production
    startCommand: node server.js
    plan: free
