server.port=${PORT:8080}
spring.application.name=zitoun-pos

# H2 dev
spring.datasource.url=jdbc:h2:mem:zitoundev;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Liquibase désactivé en dev (Hibernate crée le schéma)
spring.liquibase.enabled=false

spring.jpa.show-sql=false
spring.jpa.open-in-view=false
cors.allowed-origins=${FRONTEND_URL:*}
server.error.include-message=never
server.error.include-stacktrace=never

# JWT (dev)
jwt.secret=dYK//x5kc3HhVGv8LimPH6zgGY3xSMgpr8/EX2l11958tnFIDZeW5bpJH3xkMex+iD3a1b9hoWLzmVeaDvzGcw==
jwt.expiration-ms=28800000
